name: Ab-HADDOCK
channels:
  - r
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - biopython=1.76
  - hmmer=3.3
  - pip=19.2.3
  - python=2.7.17
  - r=3.6.0
  - r-bio3d=2.3_4
  - r-optparse=1.6.2